[
  {
    photo: "../../assets/images/insta/piece-1.png",
    name: "Deep Field, Brooklyn Dawn",
    materials: "Concrete, acrylic, ink and spray on linen",
    size: "60 x 60cm",
    sold: true,
  },
  {
    photo: "../../assets/images/insta/piece-2.png",
    name: "Three Nights in Paris, Late August.",
    materials: "Concrete, acrylic, ink and spray on linen canvas",
    size: "105 x 85cm",
    sold: true,
  },
  {
    photo: "../../assets/images/insta/piece-3.png",
    name: "Lycia, Scent of Apples",
    materials: "Concrete, acrylic, ink and spray on linen canvas.",
    size: "105 x 85cm",
    sold: true,
  },
  {
    photo: "../../assets/images/insta/piece-4.png",
    name: "The Rarer Gift of Application",
    materials: "Concrete, acrylic, ink and spray on linen canvas",
    size: "120 x 80cm",
    sold: true,
  },
  {
    photo: "../../assets/images/insta/piece-5.png",
    name: "Ouroboros II",
    materials: "Concrete, acrylic, ink and spray on linen canvas",
    size: "120 x 80cm",
    sold: true,
  },
  {
    photo: "../../assets/images/insta/piece-6.png",
    name: "July Thirteenth Madron",
    materials: "Concrete, acrylic, ink and spray on linen canvas.",
    size: "105 x 85cm",
    sold: true,
  },
  {
    photo: "../../assets/images/insta/2piece-1.png",
    name: "Day end pair, sky mirrors",
    materials: "Concrete, acrylic, ink and spray on linen canvas",
    size: "40 x 30cm, 120 x 80cm",
    sold: true,
  },
];
